"""内置模型供应商定义。"""

from typing import Any


def _qwen_chat_model(
    model_id: str,
    display_name: str,
    *,
    context_length: int,
    input_modalities: list[str] | None = None,
    max_completion_tokens: int | None = None,
    supports_reasoning_effort: bool = False,
) -> dict[str, Any]:
    """生成带 DashScope 推理兼容配置的 Qwen 聊天模型目录项。"""
    compat: dict[str, Any] = {
        "thinking_format": "enable_thinking",
        "thinking_always_send": True,
        "thinking_disable_on_non_stream": True,
        "supports_reasoning_effort": supports_reasoning_effort,
    }
    if supports_reasoning_effort:
        compat["reasoning_effort_map"] = {
            "minimal": "low",
            "low": "low",
            "medium": "medium",
            "high": "medium",
            "xhigh": "xhigh",
            "max": "xhigh",
        }

    model: dict[str, Any] = {
        "id": model_id,
        "type": "chat",
        "display_name": display_name,
        "source": "catalog",
        "context_length": context_length,
        "input_modalities": input_modalities or ["text"],
        "supported_parameters": ["tools", "temperature", "enable_thinking"],
        "compat": compat,
    }
    if max_completion_tokens is not None:
        model["max_completion_tokens"] = max_completion_tokens
    if supports_reasoning_effort:
        model["supported_parameters"].append("reasoning_effort")
    return model


# 目录参考 WeKnora 的阿里云模型定义。它只作为设置页候选，不会在启动时自动启用，
# 因而升级不会改变管理员现有的默认模型或产生新的调用费用。
QWEN_DASHSCOPE_CATALOG: list[dict[str, Any]] = [
    _qwen_chat_model(
        "qwen3.8-max",
        "Qwen3.8 Max",
        context_length=1_000_000,
        max_completion_tokens=131_072,
        input_modalities=["text", "image", "video"],
        supports_reasoning_effort=True,
    ),
    _qwen_chat_model(
        "qwen3.8-flash",
        "Qwen3.8 Flash",
        context_length=1_000_000,
        max_completion_tokens=131_072,
        input_modalities=["text", "image", "video"],
        supports_reasoning_effort=True,
    ),
    _qwen_chat_model("qwen3.7-max", "Qwen3.7 Max", context_length=1_000_000, max_completion_tokens=65_536),
    _qwen_chat_model(
        "qwen3.7-plus",
        "Qwen3.7 Plus",
        context_length=1_000_000,
        max_completion_tokens=64_000,
        input_modalities=["text", "image", "video"],
    ),
    _qwen_chat_model(
        "qwen3.7-flash",
        "Qwen3.7 Flash",
        context_length=1_000_000,
        max_completion_tokens=65_536,
        input_modalities=["text", "image", "video"],
    ),
    _qwen_chat_model("qwen3-max", "Qwen3 Max", context_length=262_144, max_completion_tokens=65_536),
    _qwen_chat_model(
        "qwen3-vl-plus",
        "Qwen3 VL Plus",
        context_length=262_144,
        max_completion_tokens=32_768,
        input_modalities=["text", "image"],
    ),
    _qwen_chat_model("qwen-plus", "Qwen Plus", context_length=1_000_000, max_completion_tokens=32_768),
    _qwen_chat_model("qwen-max", "Qwen Max", context_length=131_072, max_completion_tokens=8_192),
    _qwen_chat_model("qwen-turbo", "Qwen Turbo", context_length=1_000_000, max_completion_tokens=16_384),
    _qwen_chat_model("qwen-flash", "Qwen Flash", context_length=1_000_000, max_completion_tokens=32_768),
    {
        "id": "qwen-vl-max",
        "type": "chat",
        "display_name": "Qwen VL Max",
        "source": "catalog",
        "context_length": 131_072,
        "max_completion_tokens": 8_192,
        "input_modalities": ["text", "image"],
        "supported_parameters": ["tools", "temperature"],
    },
    {
        "id": "qwen-vl-plus",
        "type": "chat",
        "display_name": "Qwen VL Plus",
        "source": "catalog",
        "context_length": 131_072,
        "max_completion_tokens": 8_192,
        "input_modalities": ["text", "image"],
        "supported_parameters": ["tools", "temperature"],
    },
    {
        "id": "qwen3.7-text-embedding",
        "type": "embedding",
        "display_name": "Qwen3.7 Text Embedding",
        "source": "catalog",
        "dimension": 1024,
        "batch_size": 10,
    },
    {
        "id": "qwen3.7-text-embedding-flash",
        "type": "embedding",
        "display_name": "Qwen3.7 Text Embedding Flash",
        "source": "catalog",
        "dimension": 1024,
        "batch_size": 10,
    },
    {
        "id": "text-embedding-v4",
        "type": "embedding",
        "display_name": "Tongyi Text Embedding v4",
        "source": "catalog",
        "dimension": 1024,
        "batch_size": 10,
    },
    {
        "id": "text-embedding-v3",
        "type": "embedding",
        "display_name": "Tongyi Text Embedding v3",
        "source": "catalog",
        "dimension": 1024,
        "batch_size": 10,
    },
    {
        "id": "qwen3-rerank",
        "type": "rerank",
        "display_name": "Qwen3 Rerank",
        "source": "catalog",
        "batch_size": 32,
        "extra": {"rerank_protocol": "dashscope"},
    },
    {
        "id": "gte-rerank-v2",
        "type": "rerank",
        "display_name": "GTE Rerank v2",
        "source": "catalog",
        "batch_size": 32,
        "extra": {"rerank_protocol": "dashscope"},
    },
]


BUILTIN_PROVIDERS: list[dict[str, Any]] = [
    {
        "provider_id": "fluxionai",
        "display_name": "Fluxion AI",
        "base_url": "https://fluxionai.space/v1",
        "api_key_env": "FLUXIONAI_API_KEY",
        "models_endpoint": "https://fluxionai.space/v1/models",
    },
    {
        "provider_id": "openai",
        "display_name": "OpenAI",
        "base_url": "https://api.openai.com/v1",
        "api_key_env": "OPENAI_API_KEY",
        "models_endpoint": "https://api.openai.com/v1/models",
    },
    # {
    #     "provider_id": "anthropic",
    #     "display_name": "Anthropic",
    #     "base_url": "https://api.anthropic.com",
    #     "api_key_env": "ANTHROPIC_API_KEY",
    #     "models_endpoint": "https://api.anthropic.com/models",
    # },
    # {
    #     "provider_id": "google",
    #     "display_name": "Google Gemini",
    #     "base_url": "https://generativelanguage.googleapis.com",
    #     "api_key_env": "GEMINI_API_KEY",
    #     "models_endpoint": "https://generativelanguage.googleapis.com/v1beta/models",
    # },
    {
        "provider_id": "deepseek",
        "display_name": "DeepSeek",
        "base_url": "https://api.deepseek.com",
        "api_key_env": "DEEPSEEK_API_KEY",
        "models_endpoint": "https://api.deepseek.com/models",
    },
    {
        "provider_id": "alibaba-cn",
        "display_name": "阿里云百炼 DashScope",
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "embedding_base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1/embeddings",
        "rerank_base_url": "https://dashscope.aliyuncs.com/api/v1/services/rerank/text-rerank/text-rerank",
        "api_key_env": "DASHSCOPE_API_KEY",
        "capabilities": ["chat", "embedding", "rerank"],
        "models_endpoint": "https://dashscope.aliyuncs.com/compatible-mode/v1/models",
        "catalog_models": QWEN_DASHSCOPE_CATALOG,
        "_legacy_values": {
            "rerank_base_url": ["https://dashscope.aliyuncs.com/compatible-api/v1/reranks"],
        },
        "enabled_models": [
            {
                "id": "text-embedding-v4",
                "type": "embedding",
                "display_name": "text-embedding-v4",
                "dimension": 1024,
            },
            {
                "id": "qwen3-rerank",
                "type": "rerank",
                "display_name": "Qwen3 Rerank",
                "batch_size": 32,
                "extra": {"rerank_protocol": "dashscope"},
            },
        ],
    },
    {
        "provider_id": "alibaba",
        "display_name": "DashScope (International)",
        "base_url": "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
        "embedding_base_url": "https://dashscope-intl.aliyuncs.com/compatible-mode/v1/embeddings",
        "rerank_base_url": "https://dashscope-intl.aliyuncs.com/api/v1/services/rerank/text-rerank/text-rerank",
        "api_key_env": "DASHSCOPE_API_KEY",
        "capabilities": ["chat", "embedding", "rerank"],
        "models_endpoint": "https://dashscope-intl.aliyuncs.com/compatible-mode/v1/models",
        "catalog_models": QWEN_DASHSCOPE_CATALOG,
    },
    {
        "provider_id": "alibaba-coding-plan-cn",
        "display_name": "Aliyun Coding Plan",
        "base_url": "https://coding.dashscope.aliyuncs.com/v1",
        "api_key_env": "DASHSCOPE_API_KEY",
        "models_endpoint": "https://coding.dashscope.aliyuncs.com/v1/models",
    },
    {
        "provider_id": "alibaba-coding-plan",
        "display_name": "Aliyun Coding Plan (International)",
        "base_url": "https://coding-intl.dashscope.aliyuncs.com/v1",
        "api_key_env": "DASHSCOPE_API_KEY",
        "models_endpoint": "https://coding-intl.dashscope.aliyuncs.com/v1/models",
    },
    {
        "provider_id": "zhipuai",
        "display_name": "Zhipu (BigModel)",
        "base_url": "https://open.bigmodel.cn/api/paas/v4",
        "api_key_env": "ZHIPUAI_API_KEY",
        "models_endpoint": "https://open.bigmodel.cn/api/paas/v4/models",
    },
    {
        "provider_id": "zhipuai-coding-plan",
        "display_name": "Zhipu Coding Plan (BigModel)",
        "base_url": "https://open.bigmodel.cn/api/coding/paas/v4",
        "api_key_env": "ZHIPUAI_API_KEY",
        "models_endpoint": "https://open.bigmodel.cn/api/coding/paas/v4/models",
    },
    {
        "provider_id": "zai",
        "display_name": "Zhipu (Z.AI)",
        "base_url": "https://api.z.ai/api/paas/v4",
        "api_key_env": "ZAI_API_KEY",
        "models_endpoint": "https://api.z.ai/api/paas/v4/models",
    },
    {
        "provider_id": "zai-coding-plan",
        "display_name": "Zhipu Coding Plan (Z.AI)",
        "base_url": "https://api.z.ai/api/coding/paas/v4",
        "api_key_env": "ZAI_API_KEY",
        "models_endpoint": "https://api.z.ai/api/coding/paas/v4/models",
    },
    {
        "provider_id": "xiaomi-token-plan-cn",
        "display_name": "XiaomiMiMo Token Plan",
        "base_url": "https://token-plan-cn.xiaomimimo.com/v1",
        "api_key_env": "XIAOMI_MIMO_TOKEN_PLAN_API_KEY",
        "models_endpoint": "https://token-plan-cn.xiaomimimo.com/v1/models",
    },
    {
        "provider_id": "xiaomi",
        "display_name": "XiaomiMiMo",
        "base_url": "https://api.xiaomimimo.com/v1",
        "api_key_env": "XIAOMI_MIMO_API_KEY",
        "models_endpoint": "https://api.xiaomimimo.com/v1/models",
    },
    {
        "provider_id": "kimi-for-coding",
        "display_name": "Kimi Code",
        "base_url": "https://api.kimi.com/coding/v1",
        "api_key_env": "KIMI_CODE_API_KEY",
        "models_endpoint": "https://api.kimi.com/coding/v1/models",
    },
    {
        "provider_id": "moonshotai-cn",
        "display_name": "Moonshot",
        "base_url": "https://api.moonshot.cn/v1",
        "api_key_env": "MOONSHOT_API_KEY",
        "models_endpoint": "https://api.moonshot.cn/v1/models",
    },
    {
        "provider_id": "moonshotai",
        "display_name": "Moonshot (International)",
        "base_url": "https://api.moonshot.ai/v1",
        "api_key_env": "MOONSHOT_API_KEY",
        "models_endpoint": "https://api.moonshot.ai/v1/models",
    },
    {
        "provider_id": "minimax-cn",
        "display_name": "MiniMax",
        "base_url": "https://api.minimaxi.com/v1",
        "api_key_env": "MINIMAX_API_KEY",
        "models_endpoint": "https://api.minimaxi.com/v1/models",
    },
    {
        "provider_id": "minimax",
        "display_name": "MiniMax (International)",
        "base_url": "https://api.minimax.io/v1",
        "api_key_env": "MINIMAX_API_KEY",
        "models_endpoint": "https://api.minimax.io/v1/models",
    },
    {
        "provider_id": "openrouter",
        "display_name": "OpenRouter",
        "base_url": "https://openrouter.ai/api/v1",
        "api_key_env": "OPENROUTER_API_KEY",
        "capabilities": ["chat", "embedding"],
        "embedding_base_url": "https://openrouter.ai/api/v1/embeddings",
        "models_endpoint": "https://openrouter.ai/api/v1/models",
        "embedding_models_endpoint": "https://openrouter.ai/api/v1/embeddings/models",
    },
    {
        "provider_id": "modelscope",
        "display_name": "ModelScope",
        "base_url": "https://api-inference.modelscope.cn/v1",
        "api_key_env": "MODELSCOPE_ACCESS_TOKEN",
        "models_endpoint": "https://api-inference.modelscope.cn/v1/models",
    },
    {
        "provider_id": "opencode",
        "display_name": "OpenCode",
        "base_url": "https://opencode.ai/zen/v1",
        "models_endpoint": "https://opencode.ai/zen/v1/models",
    },
    {
        "provider_id": "opencode-go",
        "display_name": "OpenCode Go",
        "base_url": "https://opencode.ai/zen/go/v1",
        "models_endpoint": "https://opencode.ai/zen/go/v1/models",
    },
    {
        "provider_id": "siliconflow-cn",
        "display_name": "SiliconFlow",
        "base_url": "https://api.siliconflow.cn/v1",
        "embedding_base_url": "https://api.siliconflow.cn/v1/embeddings",
        "rerank_base_url": "https://api.siliconflow.cn/v1/rerank",
        "api_key_env": "SILICONFLOW_API_KEY",
        "capabilities": ["chat", "embedding", "rerank"],
        "models_endpoint": "https://api.siliconflow.cn/v1/models?sub_type=chat",
        "embedding_models_endpoint": "https://api.siliconflow.cn/v1/models?sub_type=embedding",
        "rerank_models_endpoint": "https://api.siliconflow.cn/v1/models?sub_type=reranker",
        "enabled_models": [
            {"id": "deepseek-ai/DeepSeek-V4-Flash", "type": "chat", "display_name": "deepseek-ai/DeepSeek-V4-Flash"},
            {"id": "Pro/MiniMaxAI/MiniMax-M2.5", "type": "chat", "display_name": "Pro/MiniMaxAI/MiniMax-M2.5"},
            {"id": "zai-org/GLM-5.2", "type": "chat", "display_name": "zai-org/GLM-5.2"},
            {
                "id": "Pro/BAAI/bge-m3",
                "type": "embedding",
                "display_name": "Pro/BAAI/bge-m3",
                "dimension": 1024,
                "batch_size": 40,
            },
            {
                "id": "BAAI/bge-m3",
                "type": "embedding",
                "display_name": "BAAI/bge-m3",
                "dimension": 1024,
                "batch_size": 40,
            },
            {
                "id": "Qwen/Qwen3-Embedding-0.6B",
                "type": "embedding",
                "display_name": "Qwen/Qwen3-Embedding-0.6B",
                "dimension": 1024,
                "batch_size": 40,
            },
            {
                "id": "Pro/BAAI/bge-reranker-v2-m3",
                "type": "rerank",
                "display_name": "Pro/BAAI/bge-reranker-v2-m3",
            },
            {
                "id": "BAAI/bge-reranker-v2-m3",
                "type": "rerank",
                "display_name": "BAAI/bge-reranker-v2-m3",
            },
        ],
    },
    {
        "provider_id": "siliconflow",
        "display_name": "SiliconFlow (International)",
        "base_url": "https://api.siliconflow.com/v1",
        "embedding_base_url": "https://api.siliconflow.com/v1/embeddings",
        "rerank_base_url": "https://api.siliconflow.com/v1/rerank",
        "api_key_env": "SILICONFLOW_GLOBAL_API_KEY",
        "capabilities": ["chat", "embedding", "rerank"],
        "models_endpoint": "https://api.siliconflow.com/v1/models?sub_type=chat",
        "embedding_models_endpoint": "https://api.siliconflow.com/v1/models?sub_type=embedding",
        "rerank_models_endpoint": "https://api.siliconflow.com/v1/models?sub_type=reranker",
    },
]
