import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, Archive, Eye, FileCheck2, FlaskConical, Plus, Radar, RefreshCw, Search, Settings, ShieldCheck} from 'lucide-react';
import './styles.css';

const api = '/api/v1';
const nav = [
  ['runs','研究任务',Archive], ['evidence','证据中心',Search], ['winning','制胜机理',Radar],
  ['capabilities','能力画像',FlaskConical], ['reports','报告评审',FileCheck2], ['settings','系统配置',Settings],
];

function App(){
  const [view,setView]=useState('runs'); const [runs,setRuns]=useState([]); const [catalog,setCatalog]=useState({routes:[],agents:[],provider:{}}); const [creating,setCreating]=useState(false); const [selected,setSelected]=useState(null);
  const load=async()=>{const [runRows,cat]=await Promise.all([request('/runs',[]),request('/catalog',{routes:[],agents:[],provider:{}})]);setRuns(runRows);setCatalog(cat)};
  useEffect(()=>{void load()},[]);
  return <div className="shell"><header><div className="brand">装备能力图像 Deep Research</div><span>企业研究工作台</span><div className="health"><i/>服务正常</div></header><aside><b>研究导航</b>{nav.map(([id,label,Icon])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)}><Icon size={17}/>{label}</button>)}</aside><main>{view==='runs'&&<RunPage runs={runs} catalog={catalog} refresh={load} creating={creating} setCreating={setCreating} open={setSelected}/>} {view!=='runs'&&<DomainPage view={view} run={selected}/>}</main>{selected&&<RunDrawer run={selected} close={()=>setSelected(null)}/>}</div>
}

function RunPage({runs,catalog,refresh,creating,setCreating,open}){return <><PageTitle title="研究任务" subtitle="市场需求挖掘、制胜机理研判与装备能力图像生成"><button title="刷新" onClick={refresh}><RefreshCw size={17}/></button><button className="primary" onClick={()=>setCreating(!creating)}><Plus size={17}/>新建研究</button></PageTitle>{creating&&<CreateRun catalog={catalog} done={()=>{setCreating(false);refresh()}}/>}<section className="toolbar"><div className="search"><Search size={15}/><input placeholder="搜索研究主题"/></div><select><option>全部状态</option><option>已排队</option><option>研究中</option><option>已完成</option></select><span>{runs.length} 项任务</span></section><section className="table"><div className="tablehead"><span>主题</span><span>路线</span><span>状态</span><span>Agent</span><span>轮次</span><span>创建人</span><span>操作</span></div>{runs.length===0?<Empty text="暂无研究任务"/>:runs.map(run=><div className="row" key={run.run_id}><span><b>{run.topic}</b><small>{run.run_id}</small></span><span>{routeLabel(run.research_route)}</span><span><Status value={run.status}/></span><span>{run.selected_agent_ids.length||'默认 4'}</span><span>{run.max_rounds}</span><span>{run.created_by}</span><span><button title="查看详情" onClick={()=>open(run)}><Eye size={16}/></button></span></div>)}</section></>}

function CreateRun({catalog,done}){const [topic,setTopic]=useState('');const [route,setRoute]=useState('new_winning_mechanism');const [agents,setAgents]=useState(catalog.agents.map(a=>a.agent_id));const routeDef=catalog.routes.find(r=>r.id===route)||{required_tags:[]};const provided=useMemo(()=>new Set(catalog.agents.filter(a=>agents.includes(a.agent_id)).flatMap(a=>a.capability_tags)),[agents,catalog]);const toggle=id=>setAgents(rows=>rows.includes(id)?rows.filter(x=>x!==id):[...rows,id]);const submit=async()=>{const created=await request('/runs',null,{method:'POST',headers:{'Content-Type':'application/json','X-Role':'analyst'},body:JSON.stringify({topic,research_route:route,selected_agent_ids:agents,max_rounds:5})});if(created){await request(`/runs/${created.run_id}/start`,null,{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID(),'X-Role':'analyst'}});done()}};return <section className="create"><div className="formgrid"><label>研究主题<input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="输入需要研判的装备能力主题"/></label><label>研究路线<select value={route} onChange={e=>setRoute(e.target.value)}>{catalog.routes.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label></div><h3>参与 Agent</h3><div className="agentgrid">{catalog.agents.map(a=><label className="agent" key={a.agent_id}><input type="checkbox" checked={agents.includes(a.agent_id)} onChange={()=>toggle(a.agent_id)}/><span><b>{a.display_name}</b><small>{a.capability_tags.join(' · ')}</small></span></label>)}</div><div className="coverage"><b>能力覆盖</b><div>{routeDef.required_tags.map(tag=><span key={tag} className={provided.has(tag)?'covered':'missing'}>{tag}</span>)}</div>{routeDef.required_tags.some(tag=>!provided.has(tag))&&<p>缺失能力将在报告中明确标注，制胜机理阶段可生成补充 Agent 建议。</p>}</div><div className="formactions"><span>模型：{catalog.provider.model||'gpt-5.5'} · 最大 5 轮</span><button className="primary" disabled={!topic.trim()||agents.length===0} onClick={submit}>创建并启动</button></div></section>}

function DomainPage({view,run}){const data={evidence:['证据卡评分与材料化状态','独立来源印证','冲突与反证分组'],winning:['L1 制胜逻辑分析','L2 概念创新评估','L3 能力图像生成'],capabilities:['新作战能力方向','现有装备升级需求','九字段文字能力画像'],reports:['五判据审计','甲方报告复核','交付产物导出'],settings:['Agent Registry','Provider 与模型配置','工具权限与上下文策略']}[view];return <><PageTitle title={nav.find(x=>x[0]===view)?.[1]} subtitle={run?`当前研究：${run.topic}`:'选择研究任务后查看对应内容'}/><section className="workspace">{data.map((item,index)=><div className="panel" key={item}><div className="panelicon"><ShieldCheck size={18}/></div><div><b>{item}</b><p>{run?'等待 worker 写入本次运行的结构化对象与审计事件。':'尚未选择研究任务。'}</p></div><span>{index+1}</span></div>)}</section></>}
function RunDrawer({run,close}){return <div className="overlay" onClick={close}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawerhead"><div><small>研究任务</small><h2>{run.topic}</h2></div><button onClick={close}>关闭</button></div><dl><dt>状态</dt><dd><Status value={run.status}/></dd><dt>研究路线</dt><dd>{routeLabel(run.research_route)}</dd><dt>参与 Agent</dt><dd>{run.selected_agent_ids.join('、')||'默认四路 Agent'}</dd><dt>最大轮次</dt><dd>{run.max_rounds}</dd></dl><h3>运行阶段</h3><div className="timeline">{['问题解析','基线 Agent','制胜机理 L1/L2/L3','五判据审计','报告输出'].map((x,i)=><div key={x}><i className={i<1?'done':''}/><span>{x}</span></div>)}</div></aside></div>}
function PageTitle({title,subtitle,children}){return <div className="title"><div><h1>{title}</h1><p>{subtitle}</p></div><div className="actions">{children}</div></div>}
function Status({value}){return <span className={`tag ${value}`}><i/>{statusLabel(value)}</span>}
function Empty({text}){return <div className="empty"><Activity size={24}/>{text}</div>}
async function request(path,fallback,options){try{const response=await fetch(`${api}${path}`,options);return response.ok?await response.json():fallback}catch{return fallback}}
function routeLabel(v){return {new_winning_mechanism:'新制胜机理',traditional_gap:'传统能力缺口',war_case_learning:'局部战争案例',auto:'自动'}[v]||v}
function statusLabel(v){return {queued:'已排队',draft:'草稿',planning:'规划中',researching:'研究中',completed:'已完成',failed:'失败'}[v]||v}
createRoot(document.getElementById('root')).render(<App/>);
