from __future__ import annotations

MISSION_LENS = '说明装备能力如何增强目标发现、火力协同、打击毁伤、反制抗扰、区域拒止、抗毁恢复或持续保障。'
QUERY_DOMINANT = True
PROFILE = {'scenario': '国外与中国国内装备现状、案例、技术路线对比及研发需求形成',
 'skills': ['equipment_osint',
            'capability_comparison',
            'technology_readiness_analysis',
            'defensive_countermeasure_analysis'],
 'tools': ['search_sources',
           'fetch_page',
           'create_evidence_card',
           'extract_parameter_observation',
           'normalize_equipment_variant',
           'reconcile_parameter_conflict',
           'assess_technology_readiness',
           'compare_equipment_capability',
           'map_defensive_countermeasure',
           'formulate_equipment_requirement'],
 'methodology': ['分别建立国外与中国国内装备谱系',
                 '按问题难点解决与核心技术路线两条主线整理案例',
                 '核验型号批次与参数条件',
                 '分析体系接口和能力边界',
                 '映射主题场景压力',
                 '按需调用颠覆种子并形成做优/拓新双轨装备族',
                 '比较防御性反制、现役升级和新研路径',
                 '定义验证计划'],
 'quality_gates': ['关键型号双源核验',
                   '冲突参数不覆盖',
                   '国内外案例、技术路线和指标均可追溯到公开证据',
                   '种子只作假设且经过对手反制、降级和成熟度校核',
                   '不凭空给出精确指标'],
 'output_focus': ['国外装备全景',
                  '中国国内装备现状',
                  '国内外具体案例',
                  '问题解决与核心技术对比',
                  '重点型号档案',
                  '体系依赖',
                  '能力边界',
                  '防御性反制',
                  '升级与新研需求',
                  '验证计划'],
 'safety_boundary': '仅使用公开来源开展战略、能力、装备市场与防御性需求研究；不得输出实时目标定位、具体攻击步骤、可直接执行的伤害行动、规避防护的方法或武器制造参数。'}
